### ISSUE TITLE
Brak informacji odnośnie przesłania drugiej pracy domowej

### ISSUE THREAD

**Issue by landmaj** [daftcode/python_levelup_2018#1]
Przy pierwszej pracy domowej podany był link do formularza, w którym należało podać adres aplikacji oraz wkleić kod.

W przypadku drugiej pracy domowej nie ma żadnej informacji, jak mamy ją dostarczyć. Musi być po prostu pod tym samym linkiem co wcześniej, a kod tym razem nie jest wymagany, czy brak informacji to jednak przeoczenie?

**Comment by pawlikowsky** [comment]
Znalezienie formularza to zapewne część zadania, inaczej byłoby za łatwo. ;]

**Comment by szpndr** [comment]
Wielkie dzięki za czujność ;) Poprawka: 997ecdceef32e2059c529eb82dcfacdc19cdc3cc
