### ISSUE TITLE
Prawidłowy sposób na obsługę błędów

### ISSUE THREAD

**Issue by jundymek** [daftcode/python_levelup_2018#10]
Mam pytanie do prowadzących odnośnie prawidłowej obsługi błędów. W rozwiązaniu pracy domowej 2 stworzyliście osobny plik z klasą do obsługi błędów i przy spełnieniu odpowiedniego warunku wyrzucacie błąd poprzez 
`raise InvalidUsage('Please provide json data')`
Czy takie obsługiwanie błędów jest gdzieś określone. Ja poszedłem po najmniejszej linii oporu i po sprawdzeniu warunku z błędem wyrzucam błąd w taki sposób:
`return json.dumps({"error": error_list}), 400`
Wcześniej oczywiście tworzę sobie listę z błędami. Chodzi mi  o wskazanie jakiegoś prawidłowego wzorca dla obsługi błędów. Domyślam się, że mój sposób nie jest właściwy, ale działa i chciałbym poznać jakiś wzorzec żeby przepisać to w prawidłowy sposób. Z góry dziękuję.

**Comment by landmaj** [comment]
Nie w temacie, ale przy okazji warto wspomnieć: używając json.dumps() zwracasz tak naprawdę stringa, bo nagłówek "Content-Type" ustawiony jest na "text/html; charset=utf-8". Sprawdzarki zadań domowych teoretycznie powinny tego nie zaakceptować jeśli wymagany był JSON i było to chyba nawet w drugiej pracy wspomniane. Lepiej użyć flaskowej funkcji jsonify(), która od razu ustawi nagłówek "Content-Type" na "application/json".

A co do twojego pytania, to nie czuję się kompetentny. :)

**Comment by jundymek** [comment]
Już się biorę za przerabianie. Oczywiście celna uwaga. Dzięki:)

**Comment by halicki** [comment]
@jundymek 
Jeżeli twój sposób działa to można uznać, że jest właściwy. Na potrzeby realizacji zadania moim zdaniem jest OK (chociaż jak zauważył @Landmaj pomija ustawienie nagłówka content - a jest to ważne).

W dalszej prespektywie można by się przyczepić do tego, że nie jest zgodny z regułą [DRY](https://pl.wikipedia.org/wiki/DRY). W skrócie: wciąż powtarzany jest ten sam fragment kodu. Jeżeli w przyszłości byś chciał zmodyfikować sposób informowania o błędzie - musiałbyś zmodofikować swój kod w wielu miejscach.

Ja poszedłem ścieżką InvalidUsage ponieważ: 
1.  pochodzi to z [przykładu z dokumentacji](http://flask.pocoo.org/docs/0.12/patterns/apierrors/) więc jest zgodny ze stylem programowania we Flasku.
2.  chciałem zademonstrować ciekawe możliwości Flaska; pokazałem tutaj jak korzystać z [errorhandler'ów](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.errorhandler). 

Te errorhandler'y są na prawdę świetne! ❤️  zwróć szczególnie uwagę na przykład z powyższego linku, pokazujący jak przygotować obsługę błędów bazy danych. Korzystając z tego nie musisz wszędzie pisać obsługi błędów - dzięki temu flask złapie i obsłuży za Ciebie błędy gdzie ich wystąpienia możesz się nawet nie spodziewać. 

Na przykład, możesz zrobić takiego error handlera, który: 
1.  złapie wszystkie nieobsłużone przez Ciebie wyjątki
2.  wrzuci raport o wystąpieniu błędu na np. [sentry](https://sentry.io/welcome/) (przy użyciu biblioteki [raven](https://docs.sentry.io/clients/python/)).
3.  użytkownikowi wyświetli ekran z informacją o zaistniałym błędzie

Podsumowując. W pracy domowej jest spoko jak używasz `return jsonify(...` ale na większe appki proponuję `@errorhandler`.
