### ISSUE TITLE
Termin oddania zadania 05

### ISSUE THREAD

**Issue by maciejbiesek** [daftcode/python_levelup_2018#14]
Hej, właśnie widzę, że zmienił się termin oddania zadania ze środy na wtorek. Widząc poprzednim razem wpis "środa" nie spojrzałem w kalendarz i nie zauważyłem, że jest to błąd (bo 10.04 był wtorkiem). Tak zaplanowałem sobie tydzień, żeby do środy do końca dnia wysłać rozwiązanie.
Czy będzie to w ogóle wzięte pod uwagę?

**Comment by jundymek** [comment]
Hmm. Podpinam się pod pytanie, bo również byłem przekonany, że terminem jest środa. Zadanie 4 zaraz wysyłam, bo dziś mam wolne i od rana siedzę przy zadaniach...

**Comment by halicki** [comment]
Wrzucajcie. ;-)
