### ISSUE TITLE
PD 3, Zad 2, 3, pytania

### ISSUE THREAD

**Issue by bloniaq** [daftcode/python_levelup_2018#5]
1. 
W zad 3 w opisie pojawia się sformułowanie:

> @log_this ma drukować w (w odpowiednim formacie) kolejności:
> 
> poziom logowania* nazwę funkcji
> argumenty wywołania
> wynik funkcji
> 
Ta gwiazdka to jak rozumiem wynik braku odstępu i nazwa funkcji to kolejny podpunkt. 
Natomiast później jest przykład działania i na pierwszym miejscu jest, o ile dobrze rozumiem, format.

> Po takim wywołaniu:
> 
> my_func(1, 2, d=True)
> Zawoła na loggerze:
> 
> logger.info(**'%s: %s -> %s'**, 'my_func', ('1', '2', 'd=True'), 'Wow!')

Prośba o uściślenie co się tam ma znaleźć. 
No chyba że czegoś nie rozumiem i to co tu widać to jest poziom logowania. ;)

2.
Z poleceń wynika, że to co mamy wklejać w formularze to sam kod dekoratora. O ile import logging jest wyraźnie zasugerowany przy rozwiązywaniu zadania 3. więc pewnie mamy go pominąć, to przy zadaniu 2. są chyba co najmniej dwa sposoby na rozbicie stringa przekazywanego do process_json. functool.wraps są wygodne, ale raczej nieistotne dla zadania. Pytanie czy mamy wklejać importy czy nie?

**Comment by ccenzura** [comment]
Dokładam pytanie, wolę się upewnić - czy json w zadaniu 2 nie powinien być podany bez ' '?
