### ISSUE TITLE
Rozwiązanie pracy domowej 2 i 3

### ISSUE THREAD

**Issue by jundymek** [daftcode/python_levelup_2018#6]
Czy byłaby możliwość wrzucenia na GitHuba przykładowego rozwiązania prac z tematu?

**Comment by arekkal515** [comment]
Podbijam

**Comment by szpndr** [comment]
Hej, wrzucone:
bc1b43faec35bea610a578d2c7371331409e65bd
3b37992043ed5c06f92a9878820fc135c46ecdda
