### ISSUE TITLE
Praca domowa 4, zadanie 1,2,5  - kolejność alfabetyczna

### ISSUE THREAD

**Issue by pan-majster** [daftcode/python_levelup_2018#7]
Chciałbym się dopytać, co dokładnie autor miał na myśli pisząc w pracy domowej o "kolejności alfabetycznej", a dokładniej czy powinniśmy przyjąć, że kolejność ta ma być czuła czy nieczuła na wielkość liter?
Jest to o tyle istotne, że w tabeli city występują zarówno miasta zaczynające się od wielkich, jak i małych liter, więc przyjęte założenie będzie miało wpływ na zwracane przez endpoint "/cities" wyniki.

W sqlite domyślnie sortowanie z wykorzystaniem "gołej" klauzuli ORDER BY jest czułe na wielkość liter czyli odwołując się do przykładu z pracy domowej, najpierw zwróci wszystkie miasta zaczynające się od wielkich liter, a na końcu te zaczynające się od małych. 

Pozdrawiam i Wesołych Świąt Wielkiej Nocy :)

**Comment by krzdabrowski** [comment]
Żeby nie zakładać kolejnego issue, mam pytanie co do zadania 4. Skoro mamy zwracać stworzony obiekt, czyli najprawdopodobniej odpowiednio SELECTować z nagłówkami kolumn, to czy zamiast "city_name" nie powinno być "city" tak jak w pliku cala_baza.png?

I dalej, żeby zachować pewną spójność - nie powinniśmy POSTować takiego samego klucza?

Pozdrawiam.

**Comment by szpndr** [comment]
@pan-majster Dzięki za zwrócenie uwagi na problem z kolejnością alfabetyczną. Lepszym rozwiązaniem jest zwracanie obiektów w kolejności alfabetycznej z wykorzystaniem `COLLATE NOCASE`: https://stackoverflow.com/questions/2413427/how-to-use-sql-order-by-statement-to-sort-results-case-insensitive .

Ponieważ nie wspomnieliśmy o tym w poleceniu, rozwiązania z samym `ORDER BY` też będą uznawane za poprawne.

@krzdabrowski prośba o zwracanie pól nazwanych tak jak w poleceniu (`"country_id"`, `"city_name"`, `"city_id"`), nie tak jak nazywają się w bazie danych.

**Comment by pan-majster** [comment]
@szpndr Dziękuję za odpowiedź.

**Comment by maciejbiesek** [comment]
@szpndr output w zadaniu 5 sugeruje żeby sortować bez wykorzystania `COLLATE NOCASE`, w przeciwnym razie otrzymamy co innego :D

**Comment by szpndr** [comment]
@maciejbiesek prawda, zakładaliśmy sortowanie bez tego. Ale skoro sortowanie z tym daje lepszy wynik, to można tego użyć. Obie wersje są dla nas poprawne teraz ;)

**Comment by rzepinskip** [comment]
@szpndr W zadaniu 4. co ma wchodzić w skład walidacji? Tworzenie miasta dla nieistniejącego kraju, tworzenie miasta o istniejącej już(w dowolnym kraju) nazwie, tworzenie miasta o istniejącej już w danym kraju nazwie?

**Comment by szpndr** [comment]
@rzepinskip Na pewno powinniśmy odrzucać request w przypadku tworzenia miasta dla nieistniejącego kraju i w przypadku tworzenia miasta o istniejącej już w danym kraju nazwie.
Jeżeli chodzi o tworzenie miasta o nazwie, która istnieje już w dowolnym kraju, to wydaje mi się, że odrzucanie tego z błędem to przesada.

Na pewno będziemy testować tę walidację, o której pisaliśmy w treści zadania, pozostałe przypadki zostawiamy Wam do pokombinowania, ale też nie planujemy ich dodatkowo testować.

**Comment by UrszulaP** [comment]
W treści zadania było napisane jedynie o odrzucanu miast dla nieistniejącego kraju, (nie było o odrzucanu miasta o istniejącej już w danym kraju nazwie). Czy muszę przesyłać swoją aplikację jeszcze raz, poprawioną, czy nie będzie to liczone jako błąd?

**Comment by maciejbiesek** [comment]
> Na pewno będziemy testować tę walidację, o której pisaliśmy w treści zadania

:)

**Comment by szpndr** [comment]
@UrszulaP będziemy testować tylko odrzucanie dla nieistniejącego kraju, ewentualne dodatkowe walidacje nie mają wpływu na naszą ocenę Waszych rozwiązań. Także nie musisz nic poprawiać ;)

**Comment by pan-majster** [comment]
Kontynuując pasjonujący temat kolejności alfabetycznej, chciałem tylko zwrócić uwagę, że Postgres domyślnie sortuje alfabetycznie jeszcze inaczej niż SQLite, co dobrze widać na przykładzie 3 pierwszych w kolejności alfabetycznej miast z bazy Sakila:
`SQLite: "A Corua (La Corua)",   "Abha",   "Abu Dhabi"`
`Postgres: "Abha",   "Abu Dhabi",   "A Corua (La Corua)"`

Wyjaśnienie tutaj: [https://stackoverflow.com/questions/34537982/incorrect-sort-collation-order-with-spaces-in-postgresql-9-4](url)

Tak więc u mnie (ale myślę że nie tylko u mnie) kolejność miast w endponcie `/cities`, będzie nieco inna w pracy domowej nr 4 niż w pracy domowej nr 5, co mam nadzieję, nie będzie traktowane jako błąd ;)
