### ISSUE TITLE
Heroku autoupdate

### ISSUE THREAD

**Issue by Sledy** [daftcode/python_levelup_2018#8]
Czy ma ktoś może problem, gdzie heroku mimo aktualnej wersji wpada w długą pętle automatycznej aktualizacji i każda komenda heroku w terminalu wykonuje się kilkanaście minut?

Podrzucam logi z CLI heroku.
[autoupdate.log](https://github.com/daftcode/python_levelup_2018/files/1871571/autoupdate.log)

P.S. Reinstalacja nie pomaga :/

**Comment by halicki** [comment]
@Sledy: Jaką komendę odpaliłeś? Wrzuciłeś tylko jej output.

**Comment by Sledy** [comment]
Przy wpisaniu jakiejkolwiek komendy heroku np. heroku login, czy heroku --version zapętla się autoupdate

**Comment by halicki** [comment]
Opisz proszę jeszcze swój setup. Jaki masz system, jak instalowałeś `heroku toolbelt`. Czy nie działało od początku, czy też może zmieniłeś coś w systemie? 
Sprawdź też informacje podane tutaj: https://devcenter.heroku.com/articles/heroku-cli#troubleshooting
Ustaw `DEBUG`, odpal jakąś komendę `heroku` i wklej nam `heroku error file`.

**Comment by halicki** [comment]
Informacyjnie dla wszystkich: problemem okazał się plik `.netrc` a raczej jego błędna zawartość. Wystarczyło usunąć go i uruchomić `heroku login` aby wszystko wróciło do normy.
