### ISSUE TITLE
INSERT do bazy

### ISSUE THREAD

**Issue by maciejbiesek** [daftcode/python_levelup_2018#9]
Cześć, po wejściu na endpoint `/actors/add`, po wpisaniu imienia, nazwiska i kliknięcia na "Dodaj" otrzymuję `sqlite3.IntegrityError: NOT NULL constraint failed: actor.actor_id`

Rozumiem, że to dlatego, że w schemacie bazy podane jest, że id nie może być NULL, nie inkrementuje się też samo z siebie. Pytanie: jak udało się to obejść na zajęciach? :)

**Comment by szpndr** [comment]
już zdradzam swój dirty hack ;)

ze schematem tabeli `actor` są dwa problemy:
1. `actor_id` nie podbija się automatycznie, więc trzeba to ustawiać ręcznie
2. w momencie dodawania nowego rekordu `last_update` jest nullem, przez co też dostajemy błąd

Polecam naprawienie tego w `DB Browserze`. Trzeba kliknąć prawy przycisk myszy -> `Modify Table` na tabeli `actor`.
1. Zaznaczyć pole `AI` koło pola `actor_id` - ustawi to opcję `autoincrement`, dzięki czemu `actor_id` będzie się automatycznie podbijać
2. Ustawić byle jaki default na na `last_update` (np. 123123) - spowoduje to, że nie wywali się błąd `NOT NULL constraint failed`, a następnie po insercie wartość ta ustawi się na taką jaka powinna być (Na tym polu jest ustawiony trigger `after insert`, który ustawia dobrą wartość). Zamiast wstawiać byle jaki default można też ewentualnie zdjąć NOT NULL z tej kolumny.

Po wprowadzeniu zmian trzeba pamiętać o kliknięciu `Write changes`.

Przed:
![screen shot 2018-04-04 at 09 56 50](https://user-images.githubusercontent.com/6171336/38295554-a65db7ca-37ee-11e8-86b4-9e8e7d2cdf77.png)
Po:
![screen shot 2018-04-04 at 09 57 08](https://user-images.githubusercontent.com/6171336/38295570-b0699a40-37ee-11e8-80df-ec9b2c5c589a.png)

**Comment by pan-majster** [comment]
Wydaje się, że odnośnie `actor_id,` wystarczające jest również samo zmienienie typu kolumny `actor_id` na `INTEGER`
[https://www.sqlite.org/lang_createtable.html#rowid](url)
ale nie wiem czy to polecane rozwiązanie :)

**Comment by szpndr** [comment]
@pan-majster masz rację, jest to dla nas wystarczające. Autoincrement zapewnia nam to, że po usuwaniu wierszy ten sam id nie zostanie ponownie już nigdy użyty, ale tutaj nam na tym nie zależy, więc `INTEGER PRIMARY KEY` jest totalnie ok ;)
